version: '3'
services:
  db:
    image: mysql:latest
    container_name: football-bd
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3307:3307  
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      
    networks:
      - football-network
  
  php:
    depends_on:
      - db
    image: php:8.1.1-apache
    container_name: football-php
    volumes:
      - "./:/var/www/html"
    ports:
      - 8000:80
      - 443:443
    networks:
      - football-network
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: football-phpMyAdmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3307
    networks:
      - football-network

networks:
  football-network:
    driver: bridge
