version: '3'

services:
  frontend:
    build: './backend'
    volumes:
      - './backend/app'
    ports:
      - '8000:80'
    networks:
      - 'fbn' #football neetwork  

  # backend:
  
  # database:

# volumes:

networks:
  fbn: